### PR TITLE
created two sub folder to support python v2 and v3

### PR DESCRIPTION
**Pull request by grepit**
I use pagerDuty API with Python and noticed some of the code is compatible with Python 2.x and some are 3.0 I cleaned up the code and create two sub folder to clearly distinguish each supported version. Thanks for taking the time to review this code and of course we are all a big fan of PagerDuty 👍

### CODE REVIEW

**Comment by grepit** [comment]
Would someone from PagerDuty team please take a look

**Comment by grepit** [comment]
@ashleyabrooks would you or someone on pagerduty team, review this pull request please ?

**Comment by Deconstrained** [comment]
Hi @nanoseconds 

Thank you for submitting your contribution, and the code clean up you've done here is especially helpful! Sorry it took us some time to get to reviewing it.

As for the v2/v3 split: considering how the only difference between the Python 2 and Python 3 files is that `print` is called as a function with parentheses in the Python 3 files (I used `diff -r`), and how this syntax is compatible with v2, I think it would make more sense to make one fileset that is compatible with both v2 and v3 (especially because the scripts are rather simple and don't have much of a chance to run into the differences between v2 and v3), rather than double the number of files that have to be maintained in this collection.

I'm going to work on a few little modifications on top of your commits, and then merge in.

Cheers!

**Comment by grepit** [comment]
np and thanks for reviewing and merging it

**Pull request merged**
